(()=>{
const NS='seven-minutes-eurovision-2027-review-8f3c1a',BASE=`https://mantledb.sh/v2/${NS}`,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={byGroup:{},openAll:false,commentMode:false,loading:false},zones=[];let toastTimer;
async function boot(){
 const app=$('#app');
 try{const parts=await Promise.all([1,2,3,4,5].map(i=>fetch(`pages-${String(i).padStart(2,'0')}.html`,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('page');return r.text()})));app.innerHTML=parts.join('\n')}catch{app.innerHTML='<section class="sheet"><h2>Could not load the memo.</h2><p>Please refresh the page.</p></section>';return}
 document.body.classList.add('review-ready');
 const bar=document.createElement('div');bar.className='review-bar';bar.dataset.reviewUi='true';bar.innerHTML='<div class="review-bar-inner"><div class="review-brand"><span class="review-dot"></span><div class="review-title">Seven Minutes <span class="review-sub">Collaborative review</span></div></div><div class="review-actions"><button class="review-pill comment-mode-btn" id="commentMode" type="button">+ Comment</button><button class="review-pill primary" id="toggleAllComments" type="button">Comments <span id="globalCommentCount">0</span></button><span class="review-status" id="reviewStatus">Connecting…</span></div></div>';document.body.prepend(bar);
 const sheets=$$('.sheet'),selected=[];const add=e=>{if(e&&!selected.some(x=>x===e||x.contains(e)))selected.push(e)};
 ['.card','.route','.tier','table','.risk','.step'].forEach(sel=>$$(sel).forEach(add));
 $$('p').forEach(p=>{if(selected.some(x=>x.contains(p)))return;const c=[...p.classList];if(c.some(x=>['lede','body','small','big-quote','note','tiny'].includes(x))||p.innerText.trim().length>90)add(p)});
 $$('ul.clean').forEach(add);selected.sort((a,b)=>a.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_FOLLOWING?-1:1);
 const counters={};selected.forEach(el=>{const sh=el.closest('.sheet');if(!sh)return;const si=sheets.indexOf(sh)+1;counters[si]=(counters[si]||0)+1;const anchor='p'+String(si).padStart(2,'0')+'-b'+String(counters[si]).padStart(2,'0'),group='page-'+String(si).padStart(2,'0');el.classList.add('commentable');const z=document.createElement('div');z.className='comment-zone';z.dataset.reviewUi='true';z.dataset.for=anchor;z.dataset.group=group;z.innerHTML='<button class="comment-marker" type="button" aria-expanded="false"><span class="marker-icon">+</span><span class="marker-label">Comment</span><span class="count"></span></button>';el.after(z);zones.push(z)});
 const toast=document.createElement('div');toast.className='review-toast';toast.id='reviewToast';toast.dataset.reviewUi='true';document.body.append(toast);wire();load(true)
}
function toast(m){const e=$('#reviewToast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1500)}
function fmt(x){try{return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(x))}catch{return''}}
function thread(z){return state.byGroup[z.dataset.group]?.[z.dataset.for]||{}}
function arr(z){return Object.entries(thread(z)).map(([id,v])=>({id,...v})).filter(x=>x&&x.text).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
function total(){return zones.reduce((n,z)=>n+arr(z).length,0)}
function updateGlobal(){const n=total(),b=$('#toggleAllComments'),c=$('#globalCommentCount');if(c)c.textContent=n;if(b)b.disabled=n===0}
function updateMarker(z){const a=arr(z),b=$('.comment-marker',z),icon=$('.marker-icon',b),label=$('.marker-label',b),count=$('.count',b);z.classList.toggle('has-comments',a.length>0);b.classList.toggle('has-comments',a.length>0);if(a.length){icon.textContent='💬';label.textContent='';count.textContent=String(a.length);b.setAttribute('aria-label',`${a.length} ${a.length===1?'comment':'comments'}`)}else{icon.textContent='+';label.textContent='Comment';count.textContent='';b.setAttribute('aria-label','Add comment')}updateGlobal()}
function buildThread(z){let t=$('.comment-thread',z);if(t)return t;t=document.createElement('div');t.className='comment-thread';t.innerHTML='<div class="comment-thread-head"><div class="comment-thread-title"></div><button class="comment-close" type="button" aria-label="Close comments">×</button></div><div class="comment-list"></div><form class="comment-form"><div class="comment-fields"><input class="comment-input comment-author" maxlength="40" placeholder="Your name" autocomplete="name" required><textarea class="comment-textarea comment-body" maxlength="1200" placeholder="Add your comment…" required></textarea></div><div class="comment-form-actions"><span class="comment-hint">Visible to everyone with this link</span><button class="comment-submit" type="submit">Post comment</button></div><div class="comment-error" role="alert"></div></form>';z.append(t);$('.comment-close',t).onclick=()=>closeThread(z);$('.comment-author',t).value=localStorage.getItem('sevenMinutesReviewName')||'';$('.comment-form',t).onsubmit=e=>submit(e,z);return t}
function render(z){updateMarker(z);const t=$('.comment-thread',z);if(!t)return;const a=arr(z),list=$('.comment-list',t),title=$('.comment-thread-title',t);title.textContent=a.length?`${a.length} ${a.length===1?'comment':'comments'}`:'Add comment';list.replaceChildren();a.forEach(c=>{const item=document.createElement('div');item.className='comment-item';const meta=document.createElement('div');meta.className='comment-meta';const n=document.createElement('span');n.className='comment-name';n.textContent=c.name||'Anonymous';const time=document.createElement('span');time.className='comment-time';time.textContent=fmt(c.createdAt);const txt=document.createElement('div');txt.className='comment-text';txt.textContent=c.text;meta.append(n,time);item.append(meta,txt);list.append(item)})}
function openThread(z){const t=buildThread(z);t.style.display='block';$('.comment-marker',z).setAttribute('aria-expanded','true');render(z);requestAnimationFrame(()=>{$('.comment-body',t)?.focus({preventScroll:true})})}
function closeThread(z){const t=$('.comment-thread',z);if(t)t.style.display='none';$('.comment-marker',z).setAttribute('aria-expanded','false')}
function setCommentMode(on){state.commentMode=on;document.body.classList.toggle('comment-mode',on);const b=$('#commentMode');b.textContent=on?'Done':'+ Comment';b.classList.toggle('active',on);if(!on)zones.forEach(z=>{if(arr(z).length===0)closeThread(z)});toast(on?'Comment mode on':'Comment mode off')}
async function getGroup(g){try{const r=await fetch(`${BASE}/${g}`,{cache:'no-store'});if(r.status===404)return{};if(!r.ok)throw new Error('load');const d=await r.json();return d&&typeof d==='object'?d:{}}catch{return state.byGroup[g]||{}}}
async function load(quiet=false){if(state.loading)return;state.loading=true;if(!quiet)$('#reviewStatus').textContent='Syncing…';try{const groups=[...new Set(zones.map(z=>z.dataset.group))],rs=await Promise.all(groups.map(async g=>[g,await getGroup(g)]));rs.forEach(([g,d])=>state.byGroup[g]=d);zones.forEach(render);$('#reviewStatus').textContent='Live'}catch{$('#reviewStatus').textContent='Offline'}finally{state.loading=false}}
async function post(z,name,text){const g=z.dataset.group,a=z.dataset.for,id=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,c={name:name.trim(),text:text.trim(),createdAt:new Date().toISOString()},patch={[a]:{[id]:c}};let r=await fetch(`${BASE}/${g}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});if(r.status===404)r=await fetch(`${BASE}/${g}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});if(!r.ok)throw new Error('post');state.byGroup[g]??={};state.byGroup[g][a]??={};state.byGroup[g][a][id]=c;render(z)}
async function submit(e,z){e.preventDefault();const f=e.currentTarget,n=$('.comment-author',f).value.trim(),x=$('.comment-body',f).value.trim(),b=$('.comment-submit',f),er=$('.comment-error',f);if(!n||!x)return;er.classList.remove('show');b.disabled=true;b.textContent='Posting…';try{await post(z,n,x);localStorage.setItem('sevenMinutesReviewName',n);$('.comment-body',f).value='';toast('Comment posted')}catch{er.textContent='Could not post right now. Please try again.';er.classList.add('show')}finally{b.disabled=false;b.textContent='Post comment'}}
function wire(){zones.forEach(z=>{$('.comment-marker',z).onclick=()=>$('.comment-thread',z)?.style.display==='block'?closeThread(z):openThread(z)});$('#commentMode').onclick=()=>setCommentMode(!state.commentMode);$('#toggleAllComments').onclick=()=>{if(total()===0)return;state.openAll=!state.openAll;zones.forEach(z=>{if(arr(z).length)state.openAll?openThread(z):closeThread(z)});$('#toggleAllComments').classList.toggle('active',state.openAll)};setInterval(()=>{if(!document.hidden)load(true)},15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load(true)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
